# .github/workflows/crowdin.yml

name: Crowdin Action

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Themes/default/languages/**'
      - 'Sources/LightPortal/Addons/**'

env:
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      if: env.CROWDIN_API_TOKEN != null
      uses: actions/checkout@v2

    - name: Crowdin Action
      if: env.CROWDIN_API_TOKEN != null
      uses: crowdin/github-action@1.0.19
      with:
        upload_sources: true
        upload_translations: false
        download_translations: false
        crowdin_branch_name: 'main'
        config: '.github/crowdin.yml'
